[package]
name = "IDDFS_Pancake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
crypto = "0.4.0"
md-5 = "0.10.5"
